// QuestPass SG — Game Data (GrabMaps API-ready)
// Each stop carries all fields needed for real API integration.
// Swap grabPlaceId and lat/lng values at integration time.

window.QUESTS = [
  {
    id: 'old-school-sg',
    name: 'Old-School Singapore',
    tagline: 'Unlock the city\'s living memory',
    theme: 'heritage',
    themeIcon: 'clock',
    duration: '4h',
    durationMins: 240,
    stops: 5,
    difficulty: 2,
    xpReward: 380,
    featured: true,
    locked: false,
    recommended: true,
    neighborhood: 'Chinatown',
    persona: ['History Buff', 'Photographer'],
    vibe: 'nostalgic',
    badgeId: 'time-keeper',
    color: '#f0bc42',
    gradient: ['#1a1200', '#2a1e00'],
    // Route-aware fields (populated by GrabMaps.getRoute at runtime)
    estimatedRouteMins: null,     // filled by getRoute()
    airportReturnETA: null,       // filled by getRouteToAirport()
    safeBufferMins: null,         // computed: flightTime - (routeMins + questMins + buffer)
    fitsTimeWindow: null,         // computed: questMins <= selectedTimeMins
    stops_data: [
      {
        id: 'os-s1',
        number: 1,
        unlocked: false,
        // ── GrabMaps fields ──────────────────────────────────────────────
        name: 'Ann Siang Hill',
        neighborhood: 'Chinatown',
        placeQuery: 'Ann Siang Hill Singapore',
        grabPlaceId: null,              // TODO: fill with real Grab Place ID
        lat: 1.2801,
        lng: 103.8454,
        fallbackLat: 1.2801,           // used if place search fails
        fallbackLng: 103.8454,
        unlockRadiusMeters: 80,
        // ── Quest content ─────────────────────────────────────────────────
        clue: 'In a street that never sleeps, red lanterns guard the oldest shophouses. Find the hill where merchants once struck gold.',
        hint: 'It\'s a leafy street off Club Street — walk uphill.',
        story: 'Ann Siang Hill was a spice trading hub in the 1800s. Clan associations ruled these terraced streets. Today, heritage bars and boutiques occupy the same tiles.',
        localTip: 'Duck into Potato Head for a cocktail in the restored shophouse interior.',
        photoChallenge: 'Photograph a lantern casting a shadow on old tiles',
        reward: { name: 'Merchant\'s Seal', symbol: '⬡', color: '#f0bc42' },
        xp: 75,
        // ── Runtime (filled by app) ───────────────────────────────────────
        resolvedLat: null,
        resolvedLng: null,
        placeSearchStatus: 'idle',     // idle | loading | success | failed | using_fallback
        distanceMeters: null,          // filled by calculateDistance()
        routeToStop: null,             // filled by getRoute()
        coords: { x: 42, y: 62 },     // map pin position (%)
      },
      {
        id: 'os-s2',
        number: 2,
        unlocked: false,
        name: 'Thian Hock Keng Temple',
        neighborhood: 'Telok Ayer',
        placeQuery: 'Thian Hock Keng Temple Singapore',
        grabPlaceId: null,
        lat: 1.2796,
        lng: 103.8468,
        fallbackLat: 1.2796,
        fallbackLng: 103.8468,
        unlockRadiusMeters: 60,
        clue: 'Follow the sound of opera where a temple watches over the crossroads. Two cultures once traded here.',
        hint: 'Look for the pagoda at the intersection of two heritage streets.',
        story: 'Built in 1839 by Hokkien immigrants who gave thanks for safe passage across the South China Sea. No nails hold the roof together — only interlocking wood.',
        localTip: 'Enter quietly at midday — the incense smoke makes for ethereal photos.',
        photoChallenge: 'Capture the roofline dragons against the city skyline',
        reward: { name: 'Sea Voyager Charm', symbol: '⚓', color: '#3d8ff5' },
        xp: 75,
        resolvedLat: null, resolvedLng: null,
        placeSearchStatus: 'idle', distanceMeters: null, routeToStop: null,
        coords: { x: 48, y: 68 },
      },
      {
        id: 'os-s3',
        number: 3,
        unlocked: false,
        name: 'Cavenagh Bridge',
        neighborhood: 'Boat Quay',
        placeQuery: 'Cavenagh Bridge Singapore',
        grabPlaceId: null,
        lat: 1.2876,
        lng: 103.8520,
        fallbackLat: 1.2876,
        fallbackLng: 103.8520,
        unlockRadiusMeters: 100,
        clue: 'A bridge once floated here. Now only murals tell its story. Find the wall where the river remembers.',
        hint: 'Near Boat Quay — look for the heritage mural trail.',
        story: 'Singapore\'s oldest bridge, built in 1869. Once banned to cattle and handcarts. The river it spans once roared with bumboats unloading spices.',
        localTip: 'Cross at dusk — the Fullerton Hotel reflection is extraordinary.',
        photoChallenge: 'Silhouette yourself on the bridge at sunset',
        reward: { name: 'River Spirit', symbol: '≋', color: '#2ecb82' },
        xp: 80,
        resolvedLat: null, resolvedLng: null,
        placeSearchStatus: 'idle', distanceMeters: null, routeToStop: null,
        coords: { x: 54, y: 58 },
      },
      {
        id: 'os-s4',
        number: 4,
        unlocked: false,
        name: 'Esplanade — Theatres on the Bay',
        neighborhood: 'Marina Bay',
        placeQuery: 'Esplanade Theatres on the Bay Singapore',
        grabPlaceId: null,
        lat: 1.2897,
        lng: 103.8557,
        fallbackLat: 1.2897,
        fallbackLng: 103.8557,
        unlockRadiusMeters: 120,
        clue: 'In a building shaped like a durian, find the stage where the nation performs for the world.',
        hint: 'It\'s on the waterfront, and it spikes the skyline.',
        story: 'Nicknamed "The Durian" for its spiky aluminum sunshades. Inside: world-class concert halls tuned to acoustic perfection.',
        localTip: 'The rooftop terrace at dusk is free, uncrowded, and one of the best views in Singapore.',
        photoChallenge: 'Find the reflection of the spikes in the bay water',
        reward: { name: 'Stage Light', symbol: '✦', color: '#e040a0' },
        xp: 80,
        resolvedLat: null, resolvedLng: null,
        placeSearchStatus: 'idle', distanceMeters: null, routeToStop: null,
        coords: { x: 60, y: 54 },
      },
      {
        id: 'os-s5',
        number: 5,
        unlocked: false,
        name: 'Padang & City Hall',
        neighborhood: 'Civic District',
        placeQuery: 'Padang Singapore',
        grabPlaceId: null,
        lat: 1.2903,
        lng: 103.8519,
        fallbackLat: 1.2903,
        fallbackLng: 103.8519,
        unlockRadiusMeters: 150,
        clue: 'The colony\'s last garden still holds court. Find the field where cricket was once king.',
        hint: 'The grandstand still stands — look toward the hill.',
        story: 'The Padang has witnessed history — WWII surrender, independence declaration, and every National Day parade since 1966.',
        localTip: 'Walk the perimeter at dusk — the neoclassical buildings are lit gold.',
        photoChallenge: 'Photograph all four heritage buildings in one frame',
        reward: { name: 'Independence Flame', symbol: '⬟', color: '#f57c30' },
        xp: 70,
        resolvedLat: null, resolvedLng: null,
        placeSearchStatus: 'idle', distanceMeters: null, routeToStop: null,
        coords: { x: 56, y: 50 },
      }
    ]
  },
  {
    id: 'hidden-hawker',
    name: 'Hidden Hawker Gems',
    tagline: 'Eat where the locals actually eat',
    theme: 'food',
    themeIcon: 'utensils',
    duration: '3h',
    durationMins: 180,
    stops: 4,
    difficulty: 1,
    xpReward: 260,
    featured: false,
    locked: false,
    recommended: true,
    neighborhood: 'Various',
    persona: ['Foodie', 'Budget Traveller'],
    vibe: 'delicious',
    badgeId: 'hawker-legend',
    color: '#f57c30',
    gradient: ['#1a0800', '#2a1200'],
    estimatedRouteMins: null, airportReturnETA: null, safeBufferMins: null, fitsTimeWindow: null,
    stops_data: [
      {
        id: 'hh-s1', number: 1, unlocked: false,
        name: 'Maxwell Food Centre',
        neighborhood: 'Chinatown',
        placeQuery: 'Maxwell Food Centre Singapore',
        grabPlaceId: null,
        lat: 1.2803, lng: 103.8441,
        fallbackLat: 1.2803, fallbackLng: 103.8441,
        unlockRadiusMeters: 100,
        clue: 'Beneath the expressway where the old market stood, find the stall where Hainanese chicken has been perfected over 40 years.',
        hint: 'Maxwell Food Centre — ask a local for "the best chicken rice".',
        story: 'Singapore\'s most iconic hawker centre. Tian Tian Chicken Rice once fed Barack Obama. The queues at noon prove it.',
        localTip: 'Arrive before 11:30am. Tian Tian sells out by 2pm.',
        photoChallenge: 'Photograph the steamed chicken with chili and dark soy',
        reward: { name: 'Hawker Star', symbol: '★', color: '#f57c30' },
        xp: 65,
        resolvedLat: null, resolvedLng: null,
        placeSearchStatus: 'idle', distanceMeters: null, routeToStop: null,
        coords: { x: 44, y: 64 },
      },
      {
        id: 'hh-s2', number: 2, unlocked: false,
        name: 'Tekka Centre',
        neighborhood: 'Little India',
        placeQuery: 'Tekka Centre Little India Singapore',
        grabPlaceId: null,
        lat: 1.3062, lng: 103.8497,
        fallbackLat: 1.3062, fallbackLng: 103.8497,
        unlockRadiusMeters: 80,
        clue: 'In the heart of Little India, a 24-hour canteen feeds the city\'s night owls. Follow the smell of banana leaf.',
        hint: 'Buffalo Road — look for the banana leaf plates.',
        story: 'The oldest wet market in Singapore. The hawker food here hasn\'t changed in 50 years.',
        localTip: 'Order teh tarik and watch the tea being poured from height.',
        photoChallenge: 'Capture a banana leaf meal with all condiments arranged',
        reward: { name: 'Spice Vial', symbol: '◈', color: '#e040a0' },
        xp: 65,
        resolvedLat: null, resolvedLng: null,
        placeSearchStatus: 'idle', distanceMeters: null, routeToStop: null,
        coords: { x: 38, y: 44 },
      },
      {
        id: 'hh-s3', number: 3, unlocked: false,
        name: 'Old Airport Road Food Centre',
        neighborhood: 'Geylang',
        placeQuery: 'Old Airport Road Food Centre Singapore',
        grabPlaceId: null,
        lat: 1.3144, lng: 103.8826,
        fallbackLat: 1.3144, fallbackLng: 103.8826,
        unlockRadiusMeters: 100,
        clue: 'Where the airport road once ended, find the coffee shop that outlasted empires.',
        hint: 'Old Airport Road Food Centre — the one near the Geylang end.',
        story: 'Opened when Paya Lebar Airport was Singapore\'s main gateway.',
        localTip: 'Try the fried carrot cake (black version). You\'ll never want the white again.',
        photoChallenge: 'Photograph the wok hei smoke rising from a live stall',
        reward: { name: 'Wok Hei Token', symbol: '⬤', color: '#f0bc42' },
        xp: 65,
        resolvedLat: null, resolvedLng: null,
        placeSearchStatus: 'idle', distanceMeters: null, routeToStop: null,
        coords: { x: 70, y: 58 },
      },
      {
        id: 'hh-s4', number: 4, unlocked: false,
        name: 'Tiong Bahru Bakery',
        neighborhood: 'Tiong Bahru',
        placeQuery: 'Tiong Bahru Bakery Singapore',
        grabPlaceId: null,
        lat: 1.2862, lng: 103.8271,
        fallbackLat: 1.2862, fallbackLng: 103.8271,
        unlockRadiusMeters: 60,
        clue: 'In Tiong Bahru, a café hides in a converted space. The kaya toast here is sacramental.',
        hint: 'Look for a café on Yong Siak Street.',
        story: 'Tiong Bahru was Singapore\'s first public housing estate. Pre-war Art Deco blocks were luxury in 1936.',
        localTip: 'The croissant is French-trained. Order two.',
        photoChallenge: 'Frame the Art Deco curves of the surrounding estate',
        reward: { name: 'Kaya Jar', symbol: '◉', color: '#2ecb82' },
        xp: 65,
        resolvedLat: null, resolvedLng: null,
        placeSearchStatus: 'idle', distanceMeters: null, routeToStop: null,
        coords: { x: 34, y: 66 },
      }
    ]
  },
  {
    id: 'heritage-shophouse',
    name: 'Heritage Shophouse Quest',
    tagline: 'Find Singapore\'s most photogenic secret streets',
    theme: 'architecture',
    themeIcon: 'camera',
    duration: '3h',
    durationMins: 180,
    stops: 4,
    difficulty: 2,
    xpReward: 310,
    featured: false,
    locked: false,
    recommended: false,
    neighborhood: 'Kampong Glam',
    persona: ['Photographer', 'Architecture Lover'],
    vibe: 'visual',
    badgeId: 'street-eye',
    color: '#7c4dcc',
    gradient: ['#0f0a1a', '#1a1228'],
    estimatedRouteMins: null, airportReturnETA: null, safeBufferMins: null, fitsTimeWindow: null,
    stops_data: [
      {
        id: 'hs-s1', number: 1, unlocked: false,
        name: 'Haji Lane',
        neighborhood: 'Kampong Glam',
        placeQuery: 'Haji Lane Singapore',
        grabPlaceId: null,
        lat: 1.3013, lng: 103.8590,
        fallbackLat: 1.3013, fallbackLng: 103.8590,
        unlockRadiusMeters: 60,
        clue: 'Where a sultan once ruled, pastel walls line a street too narrow for cars.',
        hint: 'Haji Lane, off Arab Street.',
        story: 'One of Singapore\'s narrowest streets, yet arguably its most photogenic.',
        localTip: 'Come at 9am before the crowds.',
        photoChallenge: 'Capture the entire length of the lane in one frame',
        reward: { name: 'Tile Fragment', symbol: '▦', color: '#7c4dcc' },
        xp: 78,
        resolvedLat: null, resolvedLng: null,
        placeSearchStatus: 'idle', distanceMeters: null, routeToStop: null,
        coords: { x: 58, y: 44 },
      },
      {
        id: 'hs-s2', number: 2, unlocked: false,
        name: 'Sultan Mosque',
        neighborhood: 'Kampong Glam',
        placeQuery: 'Sultan Mosque Singapore',
        grabPlaceId: null,
        lat: 1.3024, lng: 103.8590,
        fallbackLat: 1.3024, fallbackLng: 103.8590,
        unlockRadiusMeters: 80,
        clue: 'A gold-domed mosque presides over a street that smells of oud and saffron.',
        hint: 'Sultan Mosque on North Bridge Road.',
        story: 'The golden dome is made partly from donated glass bottles.',
        localTip: 'Non-Muslims may enter outside prayer times.',
        photoChallenge: 'Photograph the dome reflected in a puddle after rain',
        reward: { name: 'Golden Dome', symbol: '◯', color: '#f0bc42' },
        xp: 78,
        resolvedLat: null, resolvedLng: null,
        placeSearchStatus: 'idle', distanceMeters: null, routeToStop: null,
        coords: { x: 56, y: 42 },
      },
      {
        id: 'hs-s3', number: 3, unlocked: false,
        name: 'Koon Seng Road Terraces',
        neighborhood: 'Joo Chiat',
        placeQuery: 'Koon Seng Road Joo Chiat Singapore',
        grabPlaceId: null,
        lat: 1.3118, lng: 103.8989,
        fallbackLat: 1.3118, fallbackLng: 103.8989,
        unlockRadiusMeters: 80,
        clue: 'In Joo Chiat, a Peranakan terrace is painted so brightly it stops traffic.',
        hint: 'Koon Seng Road — look for the Peranakan tiles.',
        story: 'Peranakan architecture blends Chinese, Malay, and Dutch influences.',
        localTip: 'The blue and green tiles on the facades are each hand-painted.',
        photoChallenge: 'Find and photograph the peacock tile motif',
        reward: { name: 'Peranakan Tile', symbol: '❋', color: '#e040a0' },
        xp: 77,
        resolvedLat: null, resolvedLng: null,
        placeSearchStatus: 'idle', distanceMeters: null, routeToStop: null,
        coords: { x: 74, y: 52 },
      },
      {
        id: 'hs-s4', number: 4, unlocked: false,
        name: 'Katong Antiques Row',
        neighborhood: 'Katong',
        placeQuery: 'Katong antique shops East Coast Road Singapore',
        grabPlaceId: null,
        lat: 1.3054, lng: 103.9018,
        fallbackLat: 1.3054, fallbackLng: 103.9018,
        unlockRadiusMeters: 100,
        clue: 'On a street by the sea, heritage shops sell century-old secrets.',
        hint: 'East Coast Road, Katong.',
        story: 'Katong was the favored seaside retreat of the Peranakan elite.',
        localTip: '328 Katong Laksa. The thick noodles in rich coconut broth will haunt you.',
        photoChallenge: 'Photograph a shophouse facade showing 3 architectural influences',
        reward: { name: 'Antique Key', symbol: '⌘', color: '#f57c30' },
        xp: 77,
        resolvedLat: null, resolvedLng: null,
        placeSearchStatus: 'idle', distanceMeters: null, routeToStop: null,
        coords: { x: 78, y: 56 },
      }
    ]
  },
  {
    id: 'tiong-bahru-date',
    name: 'Date in Tiong Bahru',
    tagline: 'Singapore\'s coolest neighbourhood, stop by stop',
    theme: 'local life',
    themeIcon: 'heart',
    duration: '2h',
    durationMins: 120,
    stops: 3,
    difficulty: 1,
    xpReward: 200,
    featured: false,
    locked: false,
    recommended: false,
    neighborhood: 'Tiong Bahru',
    persona: ['Couples', 'Slow Traveller'],
    vibe: 'chill',
    badgeId: 'tiong-bahru-local',
    color: '#2ecb82',
    gradient: ['#001a10', '#002818'],
    estimatedRouteMins: null, airportReturnETA: null, safeBufferMins: null, fitsTimeWindow: null,
    stops_data: [
      {
        id: 'tb-s1', number: 1, unlocked: false,
        name: 'Tiong Bahru Bird Singing Corner',
        neighborhood: 'Tiong Bahru',
        placeQuery: 'Tiong Bahru Bird Singing Corner Singapore',
        grabPlaceId: null,
        lat: 1.2862, lng: 103.8270,
        fallbackLat: 1.2862, fallbackLng: 103.8270,
        unlockRadiusMeters: 80,
        clue: 'Where birds sing in the morning and old men gather with their cages hung in trees.',
        hint: 'Tiong Bahru Bird Singing Corner near the park.',
        story: 'Every Sunday, retired men bring their songbirds in bamboo cages to compete.',
        localTip: 'Come on Sunday morning at 7am. The combined chorus is otherworldly.',
        photoChallenge: 'Photograph a birdcage silhouette against the morning sky',
        reward: { name: 'Songbird Token', symbol: '♪', color: '#2ecb82' },
        xp: 67,
        resolvedLat: null, resolvedLng: null,
        placeSearchStatus: 'idle', distanceMeters: null, routeToStop: null,
        coords: { x: 32, y: 64 },
      },
      {
        id: 'tb-s2', number: 2, unlocked: false,
        name: 'BooksActually',
        neighborhood: 'Tiong Bahru',
        placeQuery: 'BooksActually Yong Siak Street Singapore',
        grabPlaceId: null,
        lat: 1.2858, lng: 103.8280,
        fallbackLat: 1.2858, fallbackLng: 103.8280,
        unlockRadiusMeters: 40,
        clue: 'A bookshop in a curve-windowed building, where the owner reads aloud on Sundays.',
        hint: 'BooksActually on Yong Siak Street.',
        story: 'An independent bookshop run by literary rebels who refused to go online-only.',
        localTip: 'Ask the staff for their personal recommendation.',
        photoChallenge: 'Find a book title that describes your journey so far',
        reward: { name: 'First Edition', symbol: '⬕', color: '#7c4dcc' },
        xp: 67,
        resolvedLat: null, resolvedLng: null,
        placeSearchStatus: 'idle', distanceMeters: null, routeToStop: null,
        coords: { x: 33, y: 67 },
      },
      {
        id: 'tb-s3', number: 3, unlocked: false,
        name: 'Tiong Bahru Market',
        neighborhood: 'Tiong Bahru',
        placeQuery: 'Tiong Bahru Market and Food Centre Singapore',
        grabPlaceId: null,
        lat: 1.2855, lng: 103.8263,
        fallbackLat: 1.2855, fallbackLng: 103.8263,
        unlockRadiusMeters: 80,
        clue: 'On the rooftop of a wet market, a food court feeds the whole neighbourhood at dawn.',
        hint: 'Tiong Bahru Market — take the stairs to the top floor.',
        story: 'The wet market below opens at 6am. Above it, hawkers have cooked the same dishes for 30 years.',
        localTip: 'Stall 02-08: chwee kueh. $1.20 per plate. Do not skip.',
        photoChallenge: 'Capture the ceiling fans spinning above the hawker tables',
        reward: { name: 'Market Token', symbol: '◇', color: '#f57c30' },
        xp: 66,
        resolvedLat: null, resolvedLng: null,
        placeSearchStatus: 'idle', distanceMeters: null, routeToStop: null,
        coords: { x: 35, y: 65 },
      }
    ]
  },
  {
    id: 'veg-lunch',
    name: 'Vegetarian Lunch Quest',
    tagline: 'Singapore\'s plant-based underground, revealed',
    theme: 'food',
    themeIcon: 'leaf',
    duration: '2h',
    durationMins: 120,
    stops: 3,
    difficulty: 1,
    xpReward: 180,
    featured: false,
    locked: true,
    recommended: false,
    neighborhood: 'Little India',
    persona: ['Vegetarian', 'Wellness Traveller'],
    vibe: 'nourishing',
    badgeId: 'green-eater',
    color: '#2ecb82',
    gradient: ['#001a08', '#002010'],
    estimatedRouteMins: null, airportReturnETA: null, safeBufferMins: null, fitsTimeWindow: null,
    stops_data: []
  }
];

window.BADGES = [
  { id: 'time-keeper', name: 'Time Keeper', description: 'Completed Old-School Singapore', city: 'Singapore', earned: false, color: '#f0bc42', symbol: '⬡', rarity: 'rare' },
  { id: 'hawker-legend', name: 'Hawker Legend', description: 'Completed Hidden Hawker Gems', city: 'Singapore', earned: false, color: '#f57c30', symbol: '★', rarity: 'common' },
  { id: 'street-eye', name: 'Street Eye', description: 'Completed Heritage Shophouse Quest', city: 'Singapore', earned: false, color: '#7c4dcc', symbol: '◈', rarity: 'uncommon' },
  { id: 'tiong-bahru-local', name: 'Tiong Bahru Local', description: 'Completed Date in Tiong Bahru', city: 'Singapore', earned: false, color: '#2ecb82', symbol: '♪', rarity: 'common' },
  { id: 'green-eater', name: 'Green Eater', description: 'Completed Vegetarian Lunch Quest', city: 'Singapore', earned: false, color: '#2ecb82', symbol: '◉', rarity: 'common' },
  { id: 'sg-master', name: 'Singapore Master', description: 'Complete all Singapore quests', city: 'Singapore', earned: false, color: '#e040a0', symbol: '✦', rarity: 'legendary' },
  { id: 'bkk-street', name: 'Bangkok Street Ghost', description: 'Complete a Bangkok quest', city: 'Bangkok', earned: false, locked: true, color: '#f57c30', symbol: '◎', rarity: 'rare' },
  { id: 'bali-spirit', name: 'Bali Spirit', description: 'Complete a Bali quest', city: 'Bali', earned: false, locked: true, color: '#7c4dcc', symbol: '⬟', rarity: 'uncommon' },
  { id: 'hcmc-rider', name: 'HCMC Night Rider', description: 'Complete a Ho Chi Minh quest', city: 'Ho Chi Minh City', earned: false, locked: true, color: '#f0bc42', symbol: '⬤', rarity: 'rare' },
  { id: 'kl-explorer', name: 'KL Explorer', description: 'Complete a Kuala Lumpur quest', city: 'Kuala Lumpur', earned: false, locked: true, color: '#3d8ff5', symbol: '◆', rarity: 'uncommon' },
];

window.NEIGHBORHOODS = [
  { id: 'chinatown', name: 'Chinatown', x: 42, y: 63, quests: 2, color: '#f0bc42' },
  { id: 'little-india', name: 'Little India', x: 37, y: 44, quests: 1, color: '#e040a0' },
  { id: 'kampong-glam', name: 'Kampong Glam', x: 57, y: 43, quests: 1, color: '#7c4dcc' },
  { id: 'tiong-bahru', name: 'Tiong Bahru', x: 32, y: 65, quests: 2, color: '#2ecb82' },
  { id: 'marina-bay', name: 'Marina Bay', x: 58, y: 56, quests: 1, color: '#3d8ff5' },
  { id: 'joo-chiat', name: 'Joo Chiat', x: 74, y: 53, quests: 1, color: '#f57c30' },
];
